import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import User from './models/User';
import Event from './models/Event';
import Booking from './models/Booking';

const seedData = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI as string);
        console.log('Connected to MongoDB for seeding...');

        // Clear existing data
        await User.deleteMany({});
        await Event.deleteMany({});
        await Booking.deleteMany({});

        // Create admin user
        const admin = await User.create({
            name: 'Admin User',
            email: 'admin@eventsphere.com',
            password: 'admin123',
            role: 'admin',
        });

        // Create regular user
        const user = await User.create({
            name: 'John Doe',
            email: 'john@example.com',
            password: 'user123',
            role: 'user',
        });

        console.log('Users seeded');

        // Create events
        const events = await Event.create([
            {
                title: 'Tech Summit 2026',
                description: 'Join the biggest technology summit of the year featuring keynotes from industry leaders, hands-on workshops, and networking opportunities. Explore cutting-edge innovations in AI, blockchain, cloud computing, and more.',
                category: 'Technology',
                location: 'Bangalore, India',
                date: new Date('2026-04-15'),
                time: '09:00 AM',
                price: 2999,
                totalSeats: 500,
                availableSeats: 485,
                organizer: 'TechEvents India',
                image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
                isFeatured: true,
            },
            {
                title: 'Musical Nights - AR Rahman Live',
                description: 'Experience the magic of AR Rahman live in concert. A mesmerizing evening of music featuring his greatest hits and new compositions. An unforgettable night for music lovers.',
                category: 'Music',
                location: 'Mumbai, India',
                date: new Date('2026-04-20'),
                time: '07:00 PM',
                price: 4999,
                totalSeats: 2000,
                availableSeats: 1850,
                organizer: 'Live Nation India',
                image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
                isFeatured: true,
            },
            {
                title: 'IPL Cricket Carnival',
                description: 'The ultimate cricket experience! Watch the most exciting T20 league live with premium seating, food courts, and entertainment zones. Feel the adrenaline rush of live cricket action.',
                category: 'Sports',
                location: 'Chennai, India',
                date: new Date('2026-05-01'),
                time: '04:00 PM',
                price: 1499,
                totalSeats: 5000,
                availableSeats: 4200,
                organizer: 'BCCI Events',
                image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
                isFeatured: true,
            },
            {
                title: 'Contemporary Art Exhibition',
                description: 'Discover breathtaking contemporary art from emerging and established artists. Features installations, paintings, sculptures, and interactive digital art pieces from across the globe.',
                category: 'Art',
                location: 'Delhi, India',
                date: new Date('2026-05-10'),
                time: '10:00 AM',
                price: 799,
                totalSeats: 300,
                availableSeats: 280,
                organizer: 'National Art Gallery',
                image: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800',
                isFeatured: false,
            },
            {
                title: 'Food Festival - Taste of India',
                description: 'A culinary journey through India featuring 50+ food stalls, live cooking demonstrations by celebrity chefs, food competitions, and cultural performances. Taste the diversity of Indian cuisine.',
                category: 'Food',
                location: 'Hyderabad, India',
                date: new Date('2026-05-15'),
                time: '11:00 AM',
                price: 599,
                totalSeats: 1000,
                availableSeats: 920,
                organizer: 'Foodie Collective',
                image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
                isFeatured: true,
            },
            {
                title: 'Startup Growth Summit',
                description: 'Connect with investors, mentors, and fellow entrepreneurs at India\'s premier startup event. Features pitch competitions, fireside chats, and exclusive networking sessions.',
                category: 'Business',
                location: 'Pune, India',
                date: new Date('2026-05-20'),
                time: '09:30 AM',
                price: 3499,
                totalSeats: 400,
                availableSeats: 350,
                organizer: 'Startup India Hub',
                image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
                isFeatured: false,
            },
            {
                title: 'Yoga & Wellness Retreat',
                description: 'Transform your mind and body at this 2-day wellness retreat. Includes yoga sessions with master instructors, meditation workshops, Ayurvedic consultations, and organic meals.',
                category: 'Health',
                location: 'Rishikesh, India',
                date: new Date('2026-06-01'),
                time: '06:00 AM',
                price: 5999,
                totalSeats: 150,
                availableSeats: 130,
                organizer: 'Wellness India',
                image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
                isFeatured: true,
            },
            {
                title: 'AI & Machine Learning Workshop',
                description: 'Intensive hands-on workshop on AI and ML. Learn from industry experts, work on real-world projects, and get certified. Covers deep learning, NLP, computer vision, and generative AI.',
                category: 'Education',
                location: 'Bangalore, India',
                date: new Date('2026-06-10'),
                time: '10:00 AM',
                price: 1999,
                totalSeats: 200,
                availableSeats: 180,
                organizer: 'AI Academy India',
                image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
                isFeatured: false,
            },
            {
                title: 'Bollywood Dance Night',
                description: 'Get ready to groove to the beats of Bollywood! A high-energy dance event featuring professional performances, DJ sets, and audience participation. Dress code: Bollywood glam!',
                category: 'Music',
                location: 'Jaipur, India',
                date: new Date('2026-06-15'),
                time: '08:00 PM',
                price: 1299,
                totalSeats: 800,
                availableSeats: 700,
                organizer: 'Dance India Dance Events',
                image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800',
                isFeatured: false,
            },
            {
                title: 'Marathon - Run For Health',
                description: 'Annual marathon with 5K, 10K, and 21K categories. Open to all fitness levels. Includes timing chip, finisher medal, hydration points, and post-run celebration with live music.',
                category: 'Sports',
                location: 'Kolkata, India',
                date: new Date('2026-07-01'),
                time: '05:30 AM',
                price: 999,
                totalSeats: 3000,
                availableSeats: 2800,
                organizer: 'Run India Foundation',
                image: 'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?w=800',
                isFeatured: false,
            },
            {
                title: 'Photography Masterclass',
                description: 'Learn photography from award-winning photographers. Covers landscape, portrait, street, and drone photography. Includes practical outdoor shooting sessions and post-processing techniques.',
                category: 'Education',
                location: 'Goa, India',
                date: new Date('2026-07-10'),
                time: '08:00 AM',
                price: 2499,
                totalSeats: 100,
                availableSeats: 85,
                organizer: 'Lens Academy',
                image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
                isFeatured: false,
            },
            {
                title: 'Indie Music Festival',
                description: 'Celebrate independent music at India\'s biggest indie fest. Featuring 30+ indie bands across multiple stages, art installations, food trucks, and a camping experience under the stars.',
                category: 'Music',
                location: 'Shillong, India',
                date: new Date('2026-07-20'),
                time: '02:00 PM',
                price: 3999,
                totalSeats: 1500,
                availableSeats: 1350,
                organizer: 'Indie India Collective',
                image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
                isFeatured: true,
            },
            // ========== 50 NEW EVENTS BELOW ==========
            {
                title: 'Cloud Computing Conference',
                description: 'Deep-dive into AWS, Azure, and GCP with hands-on labs, expert panels, and certifications. Perfect for DevOps engineers and cloud architects looking to level up.',
                category: 'Technology',
                location: 'Hyderabad, India',
                date: new Date('2026-04-18'),
                time: '09:00 AM',
                price: 3499,
                totalSeats: 350,
                availableSeats: 310,
                organizer: 'CloudNext India',
                image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
                isFeatured: false,
            },
            {
                title: 'Kerala Classical Music Festival',
                description: 'Three days of mesmerizing Carnatic and Hindustani classical music featuring maestros from across India. Experience the soul of Indian classical traditions.',
                category: 'Music',
                location: 'Kochi, India',
                date: new Date('2026-04-25'),
                time: '05:00 PM',
                price: 1499,
                totalSeats: 600,
                availableSeats: 520,
                organizer: 'Kerala Arts Foundation',
                image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800',
                isFeatured: false,
            },
            {
                title: 'Badminton Championship',
                description: 'Watch India\'s top badminton players compete in this electrifying championship. Includes men\'s, women\'s, and mixed doubles categories.',
                category: 'Sports',
                location: 'Lucknow, India',
                date: new Date('2026-04-28'),
                time: '10:00 AM',
                price: 799,
                totalSeats: 2000,
                availableSeats: 1750,
                organizer: 'Badminton Association of India',
                image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
                isFeatured: false,
            },
            {
                title: 'Street Art Festival',
                description: 'Witness live mural painting, graffiti art, and street performances from artists worldwide. Interactive workshops for beginners and art enthusiasts.',
                category: 'Art',
                location: 'Mumbai, India',
                date: new Date('2026-05-03'),
                time: '10:00 AM',
                price: 499,
                totalSeats: 500,
                availableSeats: 450,
                organizer: 'Urban Canvas Collective',
                image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
                isFeatured: false,
            },
            {
                title: 'Biryani Cook-Off',
                description: 'Hyderabad\'s legendary biryani festival! 30+ chefs compete for the best biryani title. Taste unlimited varieties with live cooking stations and celebrity chef appearances.',
                category: 'Food',
                location: 'Hyderabad, India',
                date: new Date('2026-05-05'),
                time: '12:00 PM',
                price: 899,
                totalSeats: 800,
                availableSeats: 680,
                organizer: 'Hyderabad Food Fest',
                image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
                isFeatured: true,
            },
            {
                title: 'Women Entrepreneurs Summit',
                description: 'Empowering women in business through mentorship, funding workshops, and networking. Features success stories from India\'s top women founders.',
                category: 'Business',
                location: 'Bangalore, India',
                date: new Date('2026-05-08'),
                time: '09:00 AM',
                price: 2499,
                totalSeats: 300,
                availableSeats: 260,
                organizer: 'WomenTech India',
                image: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800',
                isFeatured: false,
            },
            {
                title: 'Ayurveda Wellness Camp',
                description: 'A weekend of traditional Ayurvedic treatments, herbal medicine workshops, Panchakarma demos, and healthy cooking classes. Reconnect with ancient wellness wisdom.',
                category: 'Health',
                location: 'Mysore, India',
                date: new Date('2026-05-12'),
                time: '07:00 AM',
                price: 4499,
                totalSeats: 100,
                availableSeats: 80,
                organizer: 'Ayush Wellness Center',
                image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800',
                isFeatured: false,
            },
            {
                title: 'Data Science Bootcamp',
                description: 'Intensive 2-day bootcamp covering Python, SQL, Tableau, and machine learning. Includes capstone project and industry certificate.',
                category: 'Education',
                location: 'Delhi, India',
                date: new Date('2026-05-14'),
                time: '09:00 AM',
                price: 2999,
                totalSeats: 150,
                availableSeats: 130,
                organizer: 'DataMinds Academy',
                image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
                isFeatured: false,
            },
            {
                title: 'Cybersecurity Hackathon',
                description: 'Test your skills against live threats in this 24-hour cybersecurity hackathon. Prizes worth ₹5 lakhs, mentorship from CISOs, and career opportunities.',
                category: 'Technology',
                location: 'Pune, India',
                date: new Date('2026-05-17'),
                time: '08:00 AM',
                price: 1499,
                totalSeats: 200,
                availableSeats: 170,
                organizer: 'CyberShield India',
                image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
                isFeatured: false,
            },
            {
                title: 'Sufi Night Live',
                description: 'An enchanting evening of Sufi music and Qawwali. Experience the spiritual depth of Sufi traditions with renowned performers and guest artists.',
                category: 'Music',
                location: 'Delhi, India',
                date: new Date('2026-05-19'),
                time: '07:30 PM',
                price: 1999,
                totalSeats: 500,
                availableSeats: 420,
                organizer: 'Jashn-e-Sufi',
                image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
                isFeatured: false,
            },
            {
                title: 'Football Premier League Finals',
                description: 'The ultimate football showdown! Watch the top two clubs battle for the title in this electrifying final match. Premium seating, fan zones, and halftime entertainment.',
                category: 'Sports',
                location: 'Goa, India',
                date: new Date('2026-05-22'),
                time: '06:00 PM',
                price: 1299,
                totalSeats: 8000,
                availableSeats: 6500,
                organizer: 'ISL Events',
                image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
                isFeatured: true,
            },
            {
                title: 'Pottery & Ceramic Workshop',
                description: 'Learn the ancient art of pottery from master artisans. Wheel throwing, hand building, glazing, and take home your own creations. All materials included.',
                category: 'Art',
                location: 'Jaipur, India',
                date: new Date('2026-05-25'),
                time: '10:00 AM',
                price: 1299,
                totalSeats: 50,
                availableSeats: 40,
                organizer: 'Rajasthani Arts Studio',
                image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800',
                isFeatured: false,
            },
            {
                title: 'Vegan Food Expo',
                description: 'India\'s largest plant-based food expo with 100+ brands, live cooking demos, nutrition workshops, and free tastings. Discover the future of food.',
                category: 'Food',
                location: 'Mumbai, India',
                date: new Date('2026-05-28'),
                time: '10:00 AM',
                price: 399,
                totalSeats: 1500,
                availableSeats: 1300,
                organizer: 'GreenPlate India',
                image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
                isFeatured: false,
            },
            {
                title: 'Digital Marketing Masterclass',
                description: 'Learn SEO, social media marketing, Google Ads, and content strategy from industry experts. Includes live campaigns and case study analysis.',
                category: 'Business',
                location: 'Chennai, India',
                date: new Date('2026-05-30'),
                time: '09:00 AM',
                price: 3999,
                totalSeats: 200,
                availableSeats: 180,
                organizer: 'DigiGrowth Academy',
                image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
                isFeatured: false,
            },
            {
                title: 'Mental Health Awareness Walk',
                description: 'Join thousands in a walk to raise awareness about mental health. Includes expert talks, stress-relief workshops, and community support sessions.',
                category: 'Health',
                location: 'Bangalore, India',
                date: new Date('2026-06-02'),
                time: '06:30 AM',
                price: 299,
                totalSeats: 5000,
                availableSeats: 4500,
                organizer: 'MindWell Foundation',
                image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
                isFeatured: false,
            },
            {
                title: 'Robotics Championship',
                description: 'Watch student teams battle it out with their custom-built robots. Categories include sumo bots, line followers, autonomous navigation, and freestyle.',
                category: 'Education',
                location: 'Hyderabad, India',
                date: new Date('2026-06-05'),
                time: '09:00 AM',
                price: 699,
                totalSeats: 800,
                availableSeats: 700,
                organizer: 'RoboIndia Edu',
                image: 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=800',
                isFeatured: false,
            },
            {
                title: 'Blockchain & Web3 Summit',
                description: 'Explore DeFi, NFTs, DAOs, and the future of the decentralized web. Featuring live demos, panel discussions, and builder workshops.',
                category: 'Technology',
                location: 'Mumbai, India',
                date: new Date('2026-06-08'),
                time: '10:00 AM',
                price: 4499,
                totalSeats: 300,
                availableSeats: 250,
                organizer: 'Web3 India Foundation',
                image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
                isFeatured: false,
            },
            {
                title: 'Rock Concert - Agnee Live',
                description: 'Feel the energy of Agnee live on stage! One of India\'s most explosive rock bands performing their greatest hits plus new material from their upcoming album.',
                category: 'Music',
                location: 'Nagpur, India',
                date: new Date('2026-06-12'),
                time: '08:00 PM',
                price: 1799,
                totalSeats: 1200,
                availableSeats: 1000,
                organizer: 'Rock Nation Events',
                image: 'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?w=800',
                isFeatured: false,
            },
            {
                title: 'Kabaddi Super League',
                description: 'High-octane kabaddi action with India\'s best raiders and defenders. Experience thrilling matches, fan zones, and meet-and-greet with star players.',
                category: 'Sports',
                location: 'Patna, India',
                date: new Date('2026-06-14'),
                time: '05:00 PM',
                price: 599,
                totalSeats: 4000,
                availableSeats: 3500,
                organizer: 'PKL Events',
                image: 'https://images.unsplash.com/photo-1461896836934-bd45ba24e73e?w=800',
                isFeatured: false,
            },
            {
                title: 'Digital Art & NFT Showcase',
                description: 'A futuristic exhibition showcasing AI-generated art, digital sculptures, interactive installations, and an NFT marketplace for collectors.',
                category: 'Art',
                location: 'Bangalore, India',
                date: new Date('2026-06-18'),
                time: '11:00 AM',
                price: 999,
                totalSeats: 400,
                availableSeats: 350,
                organizer: 'Digital Canvas Labs',
                image: 'https://images.unsplash.com/photo-1633186710895-309db2eca9e4?w=800',
                isFeatured: false,
            },
            {
                title: 'Wine & Cheese Festival',
                description: 'Indulge in premium wines, artisanal cheeses, gourmet pairings, and live jazz music. Features wine tasting masterclasses and cheese-making workshops.',
                category: 'Food',
                location: 'Nashik, India',
                date: new Date('2026-06-20'),
                time: '04:00 PM',
                price: 2499,
                totalSeats: 250,
                availableSeats: 200,
                organizer: 'Sula Vineyards Events',
                image: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800',
                isFeatured: false,
            },
            {
                title: 'E-Commerce Growth Seminar',
                description: 'Learn how to scale your e-commerce business with Shopify, Amazon FBA, and D2C strategies. Featuring case studies from brands doing ₹100Cr+ revenue.',
                category: 'Business',
                location: 'Gurugram, India',
                date: new Date('2026-06-22'),
                time: '09:30 AM',
                price: 4999,
                totalSeats: 150,
                availableSeats: 120,
                organizer: 'eCom Academy',
                image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
                isFeatured: false,
            },
            {
                title: 'Fitness Bootcamp Weekend',
                description: 'Two days of intense workouts, CrossFit, HIIT, Zumba, and nutrition coaching. Led by celebrity fitness trainers with personalized fitness assessments.',
                category: 'Health',
                location: 'Chandigarh, India',
                date: new Date('2026-06-25'),
                time: '06:00 AM',
                price: 1999,
                totalSeats: 200,
                availableSeats: 170,
                organizer: 'FitLife India',
                image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
                isFeatured: false,
            },
            {
                title: 'UPSC Mock Interview Sessions',
                description: 'Get mentored by retired IAS officers and UPSC board members. Practice mock interviews, personality test strategies, and DAF analysis.',
                category: 'Education',
                location: 'Delhi, India',
                date: new Date('2026-06-28'),
                time: '08:00 AM',
                price: 1499,
                totalSeats: 100,
                availableSeats: 75,
                organizer: 'CivilServices Academy',
                image: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800',
                isFeatured: false,
            },
            {
                title: 'Flutter Developer Conference',
                description: 'India\'s largest Flutter conference! Learn cross-platform development, Dart mastery, state management patterns, and deploy production apps on Day 1.',
                category: 'Technology',
                location: 'Ahmedabad, India',
                date: new Date('2026-07-03'),
                time: '09:00 AM',
                price: 2499,
                totalSeats: 250,
                availableSeats: 220,
                organizer: 'FlutterIndia Community',
                image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
                isFeatured: false,
            },
            {
                title: 'EDM Beach Party',
                description: 'Dance under the stars at Goa\'s biggest EDM festival. International DJs, laser shows, fire acts, and an unforgettable beachside experience.',
                category: 'Music',
                location: 'Goa, India',
                date: new Date('2026-07-05'),
                time: '06:00 PM',
                price: 2999,
                totalSeats: 3000,
                availableSeats: 2500,
                organizer: 'Sunburn Events',
                image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800',
                isFeatured: true,
            },
            {
                title: 'Table Tennis Open Championship',
                description: 'National-level table tennis championship with players from 20+ states. Singles, doubles, and team events across all age groups.',
                category: 'Sports',
                location: 'Indore, India',
                date: new Date('2026-07-08'),
                time: '09:00 AM',
                price: 499,
                totalSeats: 1000,
                availableSeats: 850,
                organizer: 'TTFI Events',
                image: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800',
                isFeatured: false,
            },
            {
                title: 'Miniature Painting Workshop',
                description: 'Learn the exquisite art of Rajasthani miniature painting from master artists. Includes all materials, traditional techniques, and gold leaf application.',
                category: 'Art',
                location: 'Udaipur, India',
                date: new Date('2026-07-12'),
                time: '10:00 AM',
                price: 1799,
                totalSeats: 30,
                availableSeats: 22,
                organizer: 'Mewar Arts Academy',
                image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
                isFeatured: false,
            },
            {
                title: 'South Indian Coffee Festival',
                description: 'Celebrate the rich coffee heritage of South India. Filter coffee competitions, plantation tours, roasting workshops, and unlimited tastings of rare blends.',
                category: 'Food',
                location: 'Coorg, India',
                date: new Date('2026-07-14'),
                time: '08:00 AM',
                price: 699,
                totalSeats: 400,
                availableSeats: 340,
                organizer: 'Coffee Board India',
                image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800',
                isFeatured: false,
            },
            {
                title: 'Real Estate Investment Summit',
                description: 'Learn how to invest in commercial and residential real estate across India. Market analysis, legal frameworks, RERA updates, and REITs explained.',
                category: 'Business',
                location: 'Mumbai, India',
                date: new Date('2026-07-16'),
                time: '10:00 AM',
                price: 5999,
                totalSeats: 200,
                availableSeats: 160,
                organizer: 'PropTech India',
                image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                isFeatured: false,
            },
            {
                title: 'Meditation & Mindfulness Retreat',
                description: 'A 3-day silent meditation retreat in the Himalayas. Vipassana sessions, breathwork, nature walks, and organic vegetarian meals.',
                category: 'Health',
                location: 'Dharamshala, India',
                date: new Date('2026-07-18'),
                time: '05:00 AM',
                price: 7999,
                totalSeats: 60,
                availableSeats: 45,
                organizer: 'Himalayan Peace Center',
                image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
                isFeatured: false,
            },
            {
                title: 'English Literature Festival',
                description: 'Book readings, author interactions, poetry slams, and writing workshops. Featuring Pulitzer and Booker Prize-winning authors.',
                category: 'Education',
                location: 'Kolkata, India',
                date: new Date('2026-07-22'),
                time: '10:00 AM',
                price: 599,
                totalSeats: 500,
                availableSeats: 420,
                organizer: 'Kolkata Literary Society',
                image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
                isFeatured: false,
            },
            {
                title: 'DevOps & SRE Conference',
                description: 'Master Kubernetes, Docker, CI/CD pipelines, monitoring, and site reliability engineering from practitioners at top tech companies.',
                category: 'Technology',
                location: 'Bangalore, India',
                date: new Date('2026-07-25'),
                time: '09:00 AM',
                price: 3999,
                totalSeats: 400,
                availableSeats: 350,
                organizer: 'DevOps India',
                image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800',
                isFeatured: false,
            },
            {
                title: 'Jazz by the Lake',
                description: 'An intimate jazz evening by Nainital Lake. Featuring Indian and international jazz artists, craft cocktails, and gourmet bites under the stars.',
                category: 'Music',
                location: 'Nainital, India',
                date: new Date('2026-07-28'),
                time: '06:30 PM',
                price: 2499,
                totalSeats: 200,
                availableSeats: 170,
                organizer: 'Mountain Jazz Collective',
                image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
                isFeatured: false,
            },
            {
                title: 'Swimming Championship',
                description: 'National-level swimming competition with 50m, 100m, 200m, and relay events. Olympic-sized pool with underwater cameras and live timing.',
                category: 'Sports',
                location: 'Thiruvananthapuram, India',
                date: new Date('2026-08-01'),
                time: '08:00 AM',
                price: 399,
                totalSeats: 1500,
                availableSeats: 1300,
                organizer: 'Swimming Federation of India',
                image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800',
                isFeatured: false,
            },
            {
                title: 'Watercolor Painting Retreat',
                description: 'A 2-day immersive watercolor retreat in the Western Ghats. Plein air painting sessions, technique workshops, and artist critiques.',
                category: 'Art',
                location: 'Lonavala, India',
                date: new Date('2026-08-03'),
                time: '07:00 AM',
                price: 3499,
                totalSeats: 40,
                availableSeats: 30,
                organizer: 'Indian Watercolor Society',
                image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
                isFeatured: false,
            },
            {
                title: 'International Dessert Championship',
                description: 'Watch pastry chefs from 15 countries compete for the best dessert title. Unlimited tasting passes, live demos, and a chocolate fountain wonderland.',
                category: 'Food',
                location: 'Delhi, India',
                date: new Date('2026-08-05'),
                time: '11:00 AM',
                price: 1299,
                totalSeats: 600,
                availableSeats: 500,
                organizer: 'Sweet India Festival',
                image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
                isFeatured: false,
            },
            {
                title: 'FinTech Innovation Forum',
                description: 'Explore the future of banking, UPI, digital lending, and insurtech. Featuring demos from 50+ fintech startups and regulatory deep-dives.',
                category: 'Business',
                location: 'Bangalore, India',
                date: new Date('2026-08-08'),
                time: '09:30 AM',
                price: 4999,
                totalSeats: 250,
                availableSeats: 210,
                organizer: 'NASSCOM FinTech',
                image: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?w=800',
                isFeatured: false,
            },
            {
                title: 'Naturopathy & Detox Camp',
                description: 'A weekend of juice fasting, mud therapy, hydrotherapy, and naturopathic consultations. Cleanse your body and refresh your mind naturally.',
                category: 'Health',
                location: 'Pondicherry, India',
                date: new Date('2026-08-10'),
                time: '06:00 AM',
                price: 3999,
                totalSeats: 80,
                availableSeats: 60,
                organizer: 'Auroville Wellness',
                image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
                isFeatured: false,
            },
            {
                title: 'Competitive Programming Contest',
                description: 'Test your coding skills in this 6-hour competitive programming contest. Problems range from beginner to IOI level. Top 10 win job referrals.',
                category: 'Education',
                location: 'Chennai, India',
                date: new Date('2026-08-12'),
                time: '10:00 AM',
                price: 499,
                totalSeats: 500,
                availableSeats: 420,
                organizer: 'CodeChef India',
                image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800',
                isFeatured: false,
            },
            {
                title: 'React India Conference',
                description: 'The definitive React conference in India! Server components, React 19 features, Next.js, Remix, and state management deep-dives from core contributors.',
                category: 'Technology',
                location: 'Goa, India',
                date: new Date('2026-08-15'),
                time: '09:00 AM',
                price: 3499,
                totalSeats: 500,
                availableSeats: 400,
                organizer: 'React India',
                image: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=800',
                isFeatured: true,
            },
            {
                title: 'Acoustic Unplugged Night',
                description: 'An intimate acoustic evening with India\'s finest singer-songwriters. Raw, unplugged performances in a candlelit setting.',
                category: 'Music',
                location: 'Pune, India',
                date: new Date('2026-08-18'),
                time: '07:00 PM',
                price: 999,
                totalSeats: 150,
                availableSeats: 120,
                organizer: 'Acoustic Soul Collective',
                image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800',
                isFeatured: false,
            },
            {
                title: 'Pro Wrestling Showdown',
                description: 'India\'s biggest pro wrestling event! Watch trained wrestlers perform spectacular moves, tag team matches, and championship bouts.',
                category: 'Sports',
                location: 'Delhi, India',
                date: new Date('2026-08-20'),
                time: '06:00 PM',
                price: 899,
                totalSeats: 3000,
                availableSeats: 2600,
                organizer: 'CWE India',
                image: 'https://images.unsplash.com/photo-1517649281203-dad836b4abe5?w=800',
                isFeatured: false,
            },
            {
                title: 'Textile & Handloom Exhibition',
                description: 'Showcasing India\'s rich textile heritage. Handloom sarees, block prints, Kalamkari, Banarasi silk, and Pashmina from master weavers across India.',
                category: 'Art',
                location: 'Varanasi, India',
                date: new Date('2026-08-22'),
                time: '10:00 AM',
                price: 299,
                totalSeats: 1000,
                availableSeats: 850,
                organizer: 'Handloom India Trust',
                image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',
                isFeatured: false,
            },
            {
                title: 'Craft Beer Festival',
                description: 'Sample 100+ craft beers from 30+ Indian microbreweries. Beer pairing workshops, brewing demos, live music, and food trucks.',
                category: 'Food',
                location: 'Bangalore, India',
                date: new Date('2026-08-25'),
                time: '04:00 PM',
                price: 1499,
                totalSeats: 800,
                availableSeats: 650,
                organizer: 'Bangalore Brew Fest',
                image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800',
                isFeatured: false,
            },
            {
                title: 'Franchise India Expo',
                description: 'Explore 200+ franchise opportunities across F&B, retail, education, and services. Meet brand owners, attend seminars, and start your entrepreneurial journey.',
                category: 'Business',
                location: 'Delhi, India',
                date: new Date('2026-08-28'),
                time: '10:00 AM',
                price: 999,
                totalSeats: 2000,
                availableSeats: 1700,
                organizer: 'Franchise India Holdings',
                image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800',
                isFeatured: false,
            },
            {
                title: 'Prenatal Yoga & Wellness Day',
                description: 'Specially designed for expecting mothers. Gentle yoga, breathing techniques, nutrition guidance, and community support in a nurturing environment.',
                category: 'Health',
                location: 'Mumbai, India',
                date: new Date('2026-08-30'),
                time: '09:00 AM',
                price: 1299,
                totalSeats: 50,
                availableSeats: 38,
                organizer: 'MomCare Wellness',
                image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
                isFeatured: false,
            },
            {
                title: 'Space Science Workshop',
                description: 'Explore astrophysics, rocketry, and satellite design with ISRO scientists. Includes planetarium visit, telescope observation, and model rocket launch.',
                category: 'Education',
                location: 'Bangalore, India',
                date: new Date('2026-09-02'),
                time: '09:00 AM',
                price: 1499,
                totalSeats: 150,
                availableSeats: 120,
                organizer: 'Space India Foundation',
                image: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800',
                isFeatured: false,
            },
        ]);

        console.log(`${events.length} events seeded`);

        // Create some sample bookings
        const booking = await Booking.create({
            userId: user._id,
            eventId: events[0]._id,
            numberOfTickets: 2,
            totalPrice: events[0].price * 2,
            paymentStatus: 'completed',
            paymentId: 'demo_payment_001',
            bookingDate: new Date(),
            ticketQRCode: '',
        });

        console.log('Sample booking created');
        console.log('\n--- Seed Complete ---');
        console.log(`Admin: admin@eventsphere.com / admin123`);
        console.log(`User: john@example.com / user123`);
        console.log(`Events: ${events.length}`);
        console.log(`Bookings: 1`);

        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error);
        process.exit(1);
    }
};

seedData();
